### ISSUE TITLE
Alert spam with every flux sync

### ISSUE THREAD

**Issue by wavemoran** [topfreegames/fluxcloud#7]
I've been running the `justinbarrick/fluxcloud:v0.3.0` image for a while with no issues. I looked into this fork to try out a newer version. I alert to a Slack channel. It seems that on every flux sync, fluxcloud floods the webhook seemingly with a status of every prior release. It does this on every flux sync regardless of any actual changes.

This happens while running `flux:1.20.1` and `fluxcloud:v0.4.0`.

**Comment by marcosnils** [comment]
Interesting.. We're running this version in prod and we don't see this? cc @fdpeiter any thoughts?

**Comment by fdpeiter** [comment]
Hey, @wavemoran were you receiving exactly 1 changed resource before?

**Comment by wavemoran** [comment]
I would get one notification per a deployment. Sample shot
![image](https://user-images.githubusercontent.com/23364162/89570881-a4263b00-d7db-11ea-8367-f34bcc190e03.png)

**Comment by fdpeiter** [comment]
This was actually a bug. Flux wasn't sending the whole list of changed resources as events to the websocket. This is better explained [here](https://github.com/fluxcd/flux/issues/2494) and was fixed [here](https://github.com/fluxcd/flux/pull/3039).

**Comment by wavemoran** [comment]
I think I follow, and apologies if this is better directed at the flux repo, but it shows the fix is merged as of flux `1.20.0`. Am I missing some additional step?

**Comment by fdpeiter** [comment]
Actually the fix makes Flux send all changed resources now, so that's why you are seeing so many updated resources. The previous behavior of sending only the last changed resource was an error. You were probably missing several updates on your notifications. If the message is too verbose, you can add a custom message template that summarizes what's important for you. To do that, you can set up the ENV variable BODY_TEMPLATE, that's defined [here](https://github.com/topfreegames/fluxcloud/blob/master/pkg/formatters/default.go#L102), the default one is defined [here](https://github.com/topfreegames/fluxcloud/blob/master/pkg/formatters/default.go#L20).

**Comment by wavemoran** [comment]
It wasn't a matter of the old fluxcloud sending only one resource. It worked correctly and would send a notification on resources that were updated on a flux sync.

With the new fluxcloud, every flux sync sends hundreds of messages to the webhook flooding Slack before Slack kills the API connection temporarily. My fluxcloud log fills out with thousands of lines each sync. It appears to be sending out a notification for every manifest change or image update through the entire history of the repo.

**Comment by fdpeiter** [comment]
Apologize, now I follow. Could you share your flux args and one of the lines, without any sensitive data, as an example?

**Comment by wavemoran** [comment]
Happy to, it's pretty dense however. I counted around 4000 lines for a single sync "period".

It starts like this with the second log line being _very_ long. I've truncated it and highlighted some bits.

```
Request for:/v6/events
{"id":0,"serviceIDs":["\u003ccluster\u003e:clusterrolebinding/system:vpa-admission-controller","kube-system:poddisruptionbudget/pdb-kube-state-metrics","weave:deployment/memcached","\u003ccluster\u003e:customresourcedefinition/verticalpodautoscalers.autoscaling.k8s.io","srx:serviceaccount/dredd-service","srx:configmap/authn","kube-system:rolebinding/weave-net","\u003ccluster\u003e:clusterrolebinding/system:metrics-server","\u003ccluster\u003e:customresourcedefinition/tlscontexts.getambassador.io","srx:deployment/dredd-sqs-laker-jobs","\u003ccluster\u003e:clusterrolebinding/system:vpa-evictionter-binding","srx:rolebinding/dredd-service","\u003ccluster\u003e:clusterrole/system:vpa-actor","kube-system:deployment/cluster-autoscaler","weave:secret/flux-git-deploy","\u003ccluster\u003e:clusterrole/kube-state-metrics","\u003ccluster\u003e:clusterrole/ambassador","\u003ccluster\u003e:customresourcedefinition/authservices.getambassador.io","kube-system:serviceaccount/sealed-secrets-controller","\u003ccluster\u003e:clusterrolebinding/cluster-role-binding","\u003ccluster\u003e:clusterrolebinding/kube-state-metrics","srx:rolebinding/srx-all-binding","kube-system:deployment/metrics-server","\u003ccluster\u003e:clusterrolebinding/sealed-secrets-controller","kube-system:horizontalpodautoscaler/coredns","\u003ccluster\u003e:clusterrolebinding/system:metrics-reader","srx:deployment/dredd-sqs-s3-member-cas","\u003ccluster\u003e:namespace/srx","\u003ccluster\u003e:clusterrolebinding/dca","kube-system:role/sealed-secrets-key-admin","srx:service/ec-auth01","\u003ccluster\u003e:clusterrolebinding/weave-net","kube-system:deployment/kube-state-metrics","monitoring:serviceaccount/dca","\u003ccluster\u003e:clusterrole/weave-net","kube-system:service/sealed-secrets-controller","srx:role/dredd-control","kube-system:serviceaccount/vpa-admission-controller","\u003ccluster\u003e:clusterrole/cluster-autoscaler","\u003ccluster\u003e:clusterrolebinding/datadog-agent","\u003ccluster\u003e:clusterrolebinding/flux","\u003ccluster\u003e:clusterrolebinding/system:vpa-actor","\u003ccluster\u003e:clusterrolebinding/goldilocks-controller","\u003ccluster\u003e:apiservice/v1beta1.metrics.k8s.io","\u003ccluster\u003e:customresourcedefinition/mappings.getambassador.io","\u003ccluster\u003e:customresourcedefinition/ratelimitservices.getambassador.io","\u003ccluster\u003e:clusterrole/system:vpa-checkpoint-actor","\u003ccluster\u003e:clusterrole/system:metrics-server","goldilocks:deployment/goldilocks-controller","srx:configmap/authz","srx:deployment/dredd-manage","kube-system:daemonset/weave-net","\u003ccluster\u003e:clusterrolebinding/system:vpa-status-reader-binding","\u003ccluster\u003e:customresourcedefinition/kubernetesendpointresolvers.getambassador.io","kube-system:deployment/sealed-secrets-controller","\u003ccluster\u003e:clusterrole/dca",
```

It continues on like this for pages before changing it up slightly to this

```
"type":"sync","startedAt":"2020-08-06T17:16:58.809634439Z","endedAt":"2020-08-06T17:16:58.809634439Z","logLevel":"info","metadata":{"commits":[{"revision":"9a878b45edfa1d5e12359291d858956ac9793aec","message":"converts to newer fluxcloud fork"},{"revision":"4f2868c92df0ecae73577432f863afcb0ea81f01","message":"Auto-release xxx.dkr.ecr.us-west-1.amazonaws.com/authz:797c559721825f2d2e6d003ca0161237af4cc072"},{"revision":"d1224de236ee3d7717e40e29b4314d8539bc4ac9","message":"Auto-release xxx.dkr.ecr.us-west-1.amazonaws.com/authn:797c559721825f2d2e6d003ca0161237af4cc072"},{"revision":"fe902ac1d70f1154e7617b96de3eea0d3de6ecf9","message":"Auto-release xxx.dkr.ecr.us-west-2.amazonaws.com/portal_api:797c559721825f2d2e6d003ca0161237af4cc072"}
```

Again it seems to iterate through every git commit that corresponds to every manifest change or image update from flux.

Finally we get to the next lines of the log

```
Commits:

* <https://github.com/xxx/kubernetes/commit/9a878b45edfa1d5e12359291d858956ac9793aec|9a878b4>: converts to newer fluxcloud fork

* <https://github.com/xxx/kubernetes/commit/4f2868c92df0ecae73577432f863afcb0ea81f01|4f2868c>: Auto-release xxx.dkr.ecr.us-west-1.amazonaws.com/authz:797c559721825f2d2e6d003ca0161237af4cc072

* <https://github.com/xxx/kubernetes/commit/d1224de236ee3d7717e40e29b4314d8539bc4ac9|d1224de>: Auto-release xxx.dkr.ecr.us-west-1.amazonaws.com/authn:797c559721825f2d2e6d003ca0161237af4cc072
```

Again, it goes through hundreds of these back through the git history. 

Grepping for "Error" I see logs like this starting around log lines 2600 (to give you an idea how many logs are like the above).

```
Request for:/v6/events
{"id":0,"serviceIDs":["srx:deployment/authz"],"type":"autorelease","startedAt":"2020-08-06T17:16:58.809634439Z","endedAt":"2020-08-06T17:17:01.113485083Z","logLevel":"info","metadata":{"Revision":"07ba44684181448ff0fda79ae19a514e114790b0","result":{"ingress:deployment/ambassador-com":{"Status":"ignored","Error":"not included","PerContainer":null},"kube-system:daemonset/weave-net":{"Status":"ignored","Error":"not included","PerContainer":null},"kube-system:deployment/cluster-autoscaler":{"Status":"ignored","Error":"not included","PerContainer":null},"kube-system:deployment/kube-state-metrics":{"Status":"ignored","Error":"not included","PerContainer":null},"kube-system:deployment/metrics-server":
```

**Comment by wavemoran** [comment]
And here's the relevant flux and fluxcloud yaml:

```yaml
  containers:
      - name: flux
        # There are no ":latest" images for flux. Find the most recent
        # release or image version at https://hub.docker.com/r/fluxcd/flux/tags
        # and replace the tag here.
        image: docker.io/fluxcd/flux:1.20.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 3030 # informational
        livenessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh # to match location given in image's /etc/ssh/config
          readOnly: true # this will be the case perforce in K8s >=1.10
        - name: git-keygen
          mountPath: /var/fluxd/keygen # to match location given in image's /etc/ssh/config

        args:
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen

        # replace or remove the following URL
        - --git-url=git@github.com:xxx/kubernetes
        - --git-path=staging
        - --git-label=flux-staging
        - --git-ci-skip

        # include these next two to connect to an "upstream" service
        # (e.g., Weave Cloud). The token is particular to the service.
        - --connect=ws://127.0.0.1:3032

        # AWS Region to check for ECR images
        - --registry-ecr-region=us-west-1,us-west-2
        - --registry-require=ecr

        # Garbage collection logging
        - --sync-garbage-collection
      - name: fluxcloud
        image: tfgco/fluxcloud:v0.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3032
        env:
        - name: SLACK_URL
          value: "https://hooks.slack.com/services/xxx"
        - name: SLACK_CHANNEL
          value: "#deployments"
        - name: SLACK_USERNAME
          value: STAGE Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":yellow_heart:"
        - name: GITHUB_URL
          value: "https://github.com/xxx/kubernetes"
        - name: LISTEN_ADDRESS
          value: ":3032"
```
